Create zhuwenbo.md
SDIBTACM/training pull request #362
Opened 2024-03-24 04:09 UTC by SDTBUZWB

2024-03-24 06:24 UTC, Cu1ii commented on WeeklyReport/2024/20240323/zhuwenbo.md
> +存在一对非负整数（a，b），使得X＝a^3+a^2*b+a*b^2+b^3。
这种公式可以使用 latex 来写, 会好看不少

2024-03-24 06:25 UTC, Cu1ii commented on WeeklyReport/2024/20240323/zhuwenbo.md
> +Monocarp对BFS非常着迷，以至于最终失去了他的树。幸运的是，他仍然有一个顶点序列，其中BFS算法访问顶点的顺序（伪代码中的数组a）。Monocarp知道每个顶点只访问过一次（因为它们只从队列中放入和取出过一次）。此外，他知道每个顶点的所有子项都是按升序排列的。
换行要打两下回车, markdown 格式打一个换行是无效的

2024-03-24 06:25 UTC, Cu1ii requested changes
可以看下具体留言

2024-03-27 12:35 UTC, sdibt approved these changes

2024-05-19 03:14 UTC, closed without merging