Create xujnhao.md
SDIBTACM/training pull request #364
Opened 2024-03-24 04:24 UTC by xjh004

2024-03-24 06:14 UTC, Cu1ii commented on WeeklyReport/2024/20240323/xujnhao.md
> +q = Queue()
这里最好使用代码块包裹, 即使是伪代码. markdown 格式换行要两次.

2024-03-24 06:14 UTC, Cu1ii commented on WeeklyReport/2024/20240323/xujnhao.md
> +A_x A_y
这里用的是 latex 公式吗? 似乎缺少 ${} 包裹..

2024-03-24 06:21 UTC, Cu1ii requested changes
可以看一下上面的留言

2024-03-27 12:36 UTC, sdibt approved these changes

2024-05-19 03:13 UTC, closed without merging